### ISSUE TITLE
Parent POM

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#123]
We did discuss this, but IMHO we need a common (inject, plexus, mojos) shared parent POM.

OR, and this is wilder, why are these things in separate repositories at all? They are anyway released together (share same release cycle).

@mcculls @kwin

**Comment by kwin** [comment]
I am fine with consolidation in a single repo and introduction of a shared parent POM. This requires cleanup/archiving of the no longer used GitHub repos

**Comment by cstamas** [comment]
Consolidation done.
