### ISSUE TITLE
Consolidate website

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#152]
We have some "minisite" here: https://github.com/eclipse-sisu/sisu-project/tree/main/docs
But we have "the site" here: https://github.com/eclipse-sisu/sisu-website

Consolidate the two, I'd really like to have out up to date site on https://eclipse.dev/sisu/ instead of some long GH pages URL.

**Comment by cstamas** [comment]
@HomeOfTheWizard @mcculls @kwin ping

**Comment by cstamas** [comment]
Also, sisu-website is now off, contains wrong URLs, etc, we need to sort that out.

**Comment by HomeOfTheWizard** [comment]
I wasn't aware of this repo https://github.com/eclipse-sisu/sisu-website

But there is also this site that is still alive and which also have old links and info that needs to be corrected
https://projects.eclipse.org/projects/technology.sisu
I could not find the sources of it to create a PR.

BTW I can gladly help where I can on consolidating and fixing old info/links

**Comment by kwin** [comment]
> But there is also this site that is still alive and which also have old links and info that needs to be corrected
https://projects.eclipse.org/projects/technology.sisu
I could not find the sources of it to create a PR.

Good catch. This can only be maintained through a form based UI by Sisu committers unfortunately.

**Comment by HomeOfTheWizard** [comment]
I realized that using `maven-core` v3.9.6 or above in plugin dependencies, we do not need to use the `sisu-maven-plugin` anymore to create the index of annotated components, as explained [here](https://maven.apache.org/maven-jsr330.html).
I think we should update that documentation as well.

**Comment by kwin** [comment]
Look at https://github.com/eclipse-sisu/sisu-project/blob/main/README.md#generation-of-named-index. You need the index, but it is usually created through the annotation processor (if contained in the classpath).

**Comment by HomeOfTheWizard** [comment]
I think the functioning or failing of this index generation is a bit too silent.
I have a project where I was defining the `sisu-maven-plugin` explicitely before, now I just removed it (without touching the maven-compile-plugin config) and it still generates the index. 
I do not see any APT processor activated during the compilation.

here is the project: https://github.com/HomeOfTheWizard/spring-bridge-maven-plugin

**Comment by kwin** [comment]
index is optional in general, mandatory for Maven though.

**Comment by HomeOfTheWizard** [comment]
The index file is well generated in my META-INF/sisu folder, even though I did not use any of the solutions provided in the link. 
Plus I see that the APT processor is disabled by default now with your PR on the version 0.9.0.M3

**Comment by HomeOfTheWizard** [comment]
I just realized that when I upgrade from maven-core 3.9.7 to 3.9.8 the index is not generated anymore.
This validates my previous theory. I think it is because of the APT processor being desactivated in https://github.com/eclipse-sisu/sisu-project/pull/105.
So the documentation on your link is correct for the version of maven core 3.9.8.
My issue was simply that I was using 3.9.7 :)
Mea culpa

**Comment by HomeOfTheWizard** [comment]
I have created the folloing PR https://github.com/apache/maven-site/pull/550

**Comment by HomeOfTheWizard** [comment]
Also this one https://github.com/eclipse-sisu/sisu-project/pull/158

**Comment by kwin** [comment]
Here are some general remarks about Eclipse Websites: https://www.eclipse.org/projects/handbook/#resources-website and https://www.eclipse.org/projects/handbook/#trademarks-website. I would recommend getting rid of the PHP based one from https://github.com/eclipse-sisu/sisu-website but instead build one with m-site-p (as this nicely integrates with the maven plugin documentation for https://github.com/eclipse-sisu/sisu-project/tree/main/org.eclipse.sisu.mojos).

The PHP based website is based on https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/index.php.

The one at https://eclipse-sisu.github.io/sisu-project/ is being populated from https://github.com/eclipse-sisu/sisu-project/tree/main/docs (https://github.com/eclipse-sisu/.eclipsefdn/blob/main/otterdog/eclipse-sisu.jsonnet#L34).

**Comment by kwin** [comment]
The new website is now live at https://eclipse-sisu.github.io/sisu-website/ and I requested serving that from https://eclipse.dev/sisu/ as well in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4989
