### ISSUE TITLE
EPL1 still referenced (after switch to EPL2)

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#159]
We still have references to EPL 1.0 in about.html pages

https://github.com/eclipse-sisu/sisu-project/blob/main/org.eclipse.sisu.mojos/src/main/resources/about.html

**Comment by kwin** [comment]
The about.html is relevant for Eclipse Plugins only (compare with https://www.eclipse.org/projects/handbook/#legaldoc-plugins-abouts). Since we got rid of the eclipse plugin packaging and just package regular OSGi bundles I would recommend to instead just include a default LICENSE instead.

**Comment by kwin** [comment]
As we do have the `Bundle-License` header (automatically derived from the POM, https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-maven-plugin#default-bundle-headers) in each OSGi bundle there is IMHO no need for anything else.
