### ISSUE TITLE
Outdated wiki page for Plexus -> Sisu migration

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#54]
IMHO the page https://wiki.eclipse.org/Sisu/PlexusMigration contains a bit outdated information, uses `org.sonatype` package, while these annodations like [Description](https://github.com/eclipse/sisu.inject/blob/master/org.eclipse.sisu.inject/src/org/sonatype/inject/Description.java) are deprecated.

Also, do we want maybe to migrate that page here to GH wiki? Or even better into Git repo (as then PRs to fix doco could become possible).

**Comment by mcculls** [comment]
The old page has already been migrated to https://github.com/eclipse/sisu.plexus/wiki/Plexus-to-JSR330 (I need to update the eclipse wiki to point to the new pages)

**Comment by cstamas** [comment]
I still talks about org.sonatype.sisu.Description thought 😉

**Comment by cstamas** [comment]
Nvm. It is updated now

**Comment by kwin** [comment]
The canonical documentation is now at https://eclipse.dev/sisu/org.eclipse.sisu.plexus/conversion-to-jsr330.html.
