### ISSUE TITLE
Document SisuIndexAPT6 and it's presence in services

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#55]
The SisuIndexAPT6 is enlisted as [service](https://github.com/eclipse/sisu.inject/blob/master/org.eclipse.sisu.inject/META-INF/services/javax.annotation.processing.Processor).

This should be documented, as page https://www.eclipse.org/sisu/docs/api/org.eclipse.sisu.mojos/ where SisuIndexAPT6 Javadoc leads does not make any mention of it.

**Comment by slachiewicz** [comment]
> Java 6 Annotation {@link Processor} that generates a qualified class index for the current build.
maybe also change name

**Comment by kwin** [comment]
#104 is related

**Comment by kwin** [comment]
This is now documented at https://eclipse.dev/sisu/org.eclipse.sisu.inject/named-index.html.
