### ISSUE TITLE
LifecycleManager reatains classes forever

### ISSUE THREAD

**Issue by laeubi** [eclipse-sisu/sisu-project#74]
The following `Map` in `LifecycleManager`
https://github.com/eclipse/sisu.inject/blob/6fa4bc1a635f1e8ec91e438bcb059f414d713f70/org.eclipse.sisu.inject/src/org/eclipse/sisu/bean/LifecycleManager.java#L31-L32

prevents no longer used classes (and more important their classloaders) from being garbage collected, see for example 
- https://github.com/eclipse-m2e/m2e-core/issues/1214

This should use some strategies like `WeakHashMap` so if the class is only referenced from this component it could still be freed.

See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=581407

**Comment by odrotbohm** [comment]
Thanks for moving this into the right place, @laeubi! 🙇
