### ISSUE TITLE
Ability to use "external" ASM

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#83]
To prevent being locked...

Could we do something similar like explained here?
https://github.com/google/guice/pull/1657#issuecomment-1497955278

I know this is "tailored" to Maven, but actually, would be cool for all sisu using projects, as one could freely update ASM... as in Maven ASM is anyway "sealed" off.

**Comment by kwin** [comment]
We couldn’t agree on automatically embedding (and relocating) as part of the build in https://github.com/eclipse/sisu.inject/pull/72#issuecomment-1405193476. IIUC this would be a prerequisite for this feature.

**Comment by slachiewicz** [comment]
Ok so looks it works 6ecaaeaaa8bf038d4f9a2f15b295dedb6d7bcbdb

**Comment by mcculls** [comment]
https://github.com/eclipse/sisu.inject/pull/86 will add a "no_asm" variant for each release, allowing users to change the ASM version between releases without affecting other users that prefer having ASM embedded.

**Comment by cstamas** [comment]
Solved in .0.9.0.M2
