### ISSUE TITLE
Sisu Annotation Processor output is not reproducible

### ISSUE THREAD

**Issue by hboutemy** [eclipse-sisu/sisu-project#91]
see example https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/mojo/flatten-maven-plugin/flatten-maven-plugin-1.4.1.diffoscope
 I imagine (I did not really investigate fully) that it's linked to Annotation Processor way of generating the file

**Comment by mcculls** [comment]
This was fixed by https://github.com/eclipse/sisu.inject/commit/570e81a025ad9e462c06e0cdadb30d787052b1e6 which went into the 0.9.0.M1 milestone.

**Comment by hboutemy** [comment]
oh, stupid me, thanks for the pointer
